[build]
  functions = "functions" # Pasta onde as funções Lambda são geradas
  publish = "public"      # Pasta onde seus arquivos estáticos estão localizados (se aplicável)

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200